# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73e78721e032fde85382ae69b0927d5d01e6f8c47903cfa5fc58abcd93ec515e183572df3d26477196655dc2866d1bfe89c72a3ec2a880969bb603a2ec16ae08

test:
  secret_key_base: 6075cf655f9ec58911649fbc1d2266133c397b11b60138ff391d58270615d70b04da94f68110be8f97ee540880310d1653502e8ca0ae286bf88e56daf4367063

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
